### ISSUE TITLE
Support for ID tokens

### ISSUE THREAD

**Issue by kbanman** [Lokicoule/nestjs-cognito#174]
Hi, I'd like to use ID tokens instead of access tokens because they contain the custom attributes I need for just about every request. From a quick test it seems only access tokens work with this library.

If it's just a matter of implementing this I'd be happy to give it a go.

**Comment by Lokicoule** [comment]
Hello Kelly,

Thank you for your interest in this project!

Access tokens and ID tokens both work.
The fact is, the method [GetUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html) is waiting for 

> {
>    "[AccessToken](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html#CognitoUserPools-GetUser-request-AccessToken)": "string"
> }

That's why I suggest using an Access token instead of an ID token.

I tried to reproduce this issue in a project and it works fine with the ID token, but the OAuth 2.0 openid needs to be checked.
<img width="588" alt="image" src="https://user-images.githubusercontent.com/9872839/206451473-549e1b65-6ed1-4d87-80b5-8c019e73fc31.png">

If for some reason you are still having a problem using the ID token, can you please provide more detail on your AWS Cognito configuration?

**Comment by Lokicoule** [comment]
```
Authentication without request to Cognito.
Unless I'm misunderstanding something, each guarded request will result in a request to Cognito. This results in unnecessary latency and is rather contrary to the concept of the JWT, as all we should need to do is verify that the token was signed by the correct iss. 
```
I thought it was an acceptable compromise between ease of use and security.
Actually I wanted minimal setup, as you can see we only have to reference the region setting.
In order to get the issuer, we need the region and the usergroup id, and I don't know why, but I took note about the credentials* access key and of the secret access key that do not seem necessary.
So you are correct and I will rewrite this part as soon as possible.

```
The Cognito access token does not have the user details (or groups, iirc) in the JWT. If that token type is used we would still need to query Cognito.
```
If the openid is allowed, the cognito access token contains the user details (at least the groups) in the JWT.
The "problem" if we query Cognito for example to get the groups is the need for the access key and the secret access key to use the admin command and some people don't want to use a module that needs credentials.

```
A cool feature here would be to only fetch the user (for access tokens) on routes that actually ask for the user parameter to be injected.
```
Yes it's a very cool feature which will need to have two types of guards. One to use when we want the user, and the other one when we dont need it. I'm just scared about the complexity for the developpers who will use that modules. The documentation will need to be very well discribed and exhaustifs.

```
Extended user attributes
In my multi-tenant use case each user has a custom cognito attribute that specifies the tenant ID, which is usually required to fulfil the request. Ideally I could access custom attributes with some type safety by supplying a custom user model, but even just an untyped accessor for custom attributes would be alright.
```

I think the second scenario is the best, it will be easy to
implement by adding a custom decorator that returns an uncontrolled user and all their attributes.

NB: The credentials were for the `getSigningCertificate` method which I misunderstood the use.

**Comment by Lokicoule** [comment]
Hey Kelly,

All of the changes you wanted to see have now been integrated and I think it's looking great.

I would really appreciate it if you could take some time to take a look at the project and let me know if there is anything else you would like to see or if there are any further changes that need to be made.

Thank you again for your contributions, and I look forward to hearing from you soon!

**Comment by Lokicoule** [comment]
Release version 1.0.0.
