### ISSUE TITLE
Question: db query in authguard.

### ISSUE THREAD

**Issue by ikeda1729** [Lokicoule/nestjs-cognito#713]
In the authguard, I would like to set a current user like
```
const userFromDB = //some query
request[COGNITO_JWT_PAYLOAD_CONTEXT_PROPERTY] = {currentUser: userFromDB}
```

Is there any good way to do this, other than monkey patch?

**Comment by Lokicoule** [comment]
If your purpose is only for providing a domain user to your controllers or resolvers, it's not the best place to do that.
It should be better to create a new user decorator and use it instead of the `@CognitoUser`decorator.
This way, you have a better SoC and you query your DB only when you need it and not on every request.

**Comment by ikeda1729** [comment]
Yes, making `@CurrentUser` sounds better.
Thank you.

**Comment by Lokicoule** [comment]
Hello @ikeda1729, this approach sounds better than decorator one querying DB #771
