### ISSUE TITLE
Question | Update tokens

### ISSUE THREAD

**Issue by yanphilippe** [Lokicoule/nestjs-cognito#850]
Hello, 

First of all thanks for this useful library.  We are using the IdToken and registered the module (see below). 
How can I update the tokens when the IdToken expires ? Does **[nestjs-cognito](https://github.com/Lokicoule/nestjs-cognito)** has a flag to be set up in order to automatically update the tokens ?

```typescript 
 CognitoAuthModule.registerAsync({
      imports: [ConfigurationModule],
      inject: [ApiConfigurationService],
      useFactory: async (configurationService: ApiConfigurationService) => ({
        jwtVerifier: {
          userPoolId: configurationService.AWS_COGNITO_USER_POOL_ID,
          clientId: configurationService.AWS_COGNITO_CLIENT_ID,
          tokenUse: 'id',
        },
      }),
    }),
```

Thanks in advance.

**Comment by Lokicoule** [comment]
Hello @yanphilippe,

Amazon encourages token refreshing from the client side, which is why this library doesn't offer that specific feature.
For Amplify users, token refreshing is managed automatically by Auth.currentSession() behind the scenes.
But, if you're using [amazon-cognito-identity-js](https://chat.openai.com/c/amazon-cognito-identity-js) directly, you can find guidance on token refreshing [here](https://github.com/Lokicoule/react-boilerplate/blob/main/src/libs/cognito/index.ts).

**Comment by yanphilippe** [comment]
Thanks for your quick reply @Lokicoule, will do refreshing from the front end.
